### ISSUE TITLE
Flipped vertical component

### ISSUE THREAD

**Issue by jsaul** [SeisComP/main#12]
Normally for a vertical-component stream the `dip` is -90 degrees. If a vertical component is flipped, this is indicated in the inventory by a `dip` value of +90 degrees. An example is `IU.TIXI.00.BHZ`.

When plotting the traces e.g. in the `scolv` picker window, the flipped traces need to be inverted. This does not happen.

As a consequence, e.g. when measuring onset polarities, the wrong polarity is obtained.

**Comment by gempa-jabe** [comment]
Rotate your traces into ZNE system ...
