### ISSUE TITLE
fdsnws & twisted threadpool error

### ISSUE THREAD

**Issue by filefolder** [SeisComP/main#18]
Hi, this error is repeatedly showing up in our fdsnws.log (forgive the formatting)

`2021/05/06 00:33:12 [error/log] 'RequestOptions' object has no attribute 'matchTimeSeries' ['  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext\n    result = inContext.theWork()\n', '  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n', '  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n', '  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext\n    return func(*args,**kw)\n', '  File "/Rdata/seiscomp/lib/python/seiscomp/fdsnws/station.py", line 381, in _processRequestExp\n    skipRestricted)\n', '  File "/Rdata/seiscomp/lib/python/seiscomp/fdsnws/station.py", line 706, in _processStation\n    for stream in ro.streamIter(net, sta, loc, True, dac):\n', '  File "/Rdata/seiscomp/lib/python/seiscomp/fdsnws/station.py", line 228, in streamIter\n    if dac is not None and ro.matchTimeSeries:\n']`

fdsnws is otherwise up and running seemingly normally. Only recent change is adding "availability" service recently, possibly related?

python3-twisted version is 17.9.0-2ubuntu0.1 and it is latest 4.5.0 built on python 3.6 

Any help appreciated as usual

**Comment by gempa-stephan** [comment]
This is a bug related to POST requests and DataAvailability turned on. Line 228 of `seiscomp/lib/python/seiscomp/fdsnws/station.py` should read

```
if dac is not None and self.matchTimeSeries:
```

I'll create fix for this. Meanwhile you may change the line in your installation or disable the DataAvailability feature.

**Comment by gempa-stephan** [comment]
I created the PR #20 which was just merged into master. The version number was increased to 1.1.3 and new test cases have been added.
