### ISSUE TITLE
[scart] Exception when using `resample|dec` record streams

### ISSUE THREAD

**Issue by damb** [SeisComP/main#21]
When running `scart` with either a `resample://` or a `dec://` record stream configured the program prints an exception i.e.

```
Exception: <built-in function Array_bytes> returned a result with an error set
```

and no data is written. Besides of testing with a `file://` *proxy stream* I also tested with a `fdsnws://` *proxy stream* leading to the same issue. The data itself shouldn't be the issue, since I tested with different input data (from different data centers), too.

**Reproducer**:

- Python 3.8.10
- SeisComP upstream from `master`

```
$ cat scart.list
2020-10-25T19:30:00;2020-10-25T19:35:00;GR.BFO..HHZ
```

```
$ scart -v -I "resample://file/$(realpath GR.BFO..HHZ.mseed)" --list scart.list --stdout 
Archive: /home/damb/seiscomp/var/lib/archive/
Mode: IMPORT
10:03:55 [debug/Environment] Setting installdir from $SEISCOMP_ROOT: /home/damb/seiscomp
10:03:55 [info/Environment] using local config dir: /home/damb/.seiscomp
10:03:55 [debug/RecordStream] trying to open stream resample://file//home/damb/tmp/GR.BFO..HHZ.mseed
adding stream: 2020-10-25 19:30:00.000 2020-10-25 19:35:00.000 GR.BFO..HHZ
10:03:55 [debug/Resample] [dec] caching 41 coefficents for N=2
10:03:56 [debug/Resample] [dec] caching 1001 coefficents for N=50
Exception: <built-in function Array_bytes> returned a result with an error set
10:03:56 [debug/Resample] Closing proxy source
```

**Resources**:
- [GR.BFO..HHZ.txt](https://github.com/SeisComP/main/files/6590748/GR.BFO.HHZ.txt)  (the file contains miniseed records covering the time window specified in `scart.list`; renamed due to GitHub upload policies)

**Comment by gempa-jabe** [comment]
Please note that a decimated recordstream will not return MiniSEED records but internal raw arrays. So the data will be just a memory block of n integers (no header, no nothing). Maybe Python does not like to print that byte sequence.

**Comment by damb** [comment]
You refer to e.g. https://github.com/SeisComP/common/blob/a3d88b39ba6b2aff2fcfed287333fee925cc1417/libs/seiscomp/io/recordstream/resample.cpp#L351-L378? I wasn't aware of this detail.

> Maybe Python does not like to print that byte sequence.

Well, then it would be good to allow passing only those RecordStream implementations which return MiniSEED data (or at least data which can be written be `scart`). The exception is not very clear to the end user. Initially, I assumed there is an issue with the corresponding RecordStream implementation.

**Comment by gempa-jabe** [comment]
We do not know which type a recordstream returns. I have tested a fix which creates always MiniSEED if the returned record is not a MiniSEED record:

```diff
diff --git a/apps/python/scart.py b/apps/python/scart.py
index a98034d4c..6539bc67f 100644
--- a/apps/python/scart.py
+++ b/apps/python/scart.py
@@ -24,6 +24,7 @@ if sys.version_info < (2, 4):
     from sets import Set as set
 import seiscomp.core, seiscomp.client, seiscomp.config
 import seiscomp.io, seiscomp.logging, seiscomp.system
+import seiscomp.utils
 from getopt import getopt, GetoptError
 import bisect
 
@@ -765,9 +766,13 @@ else:
     f = None
     accessedFiles = set()
     try:
+        os = seiscomp.utils.file2ostream("-")
         for rec in input:
             if stdout:
-                out.write(rec.raw().str())
+                if rec.typeInfo() != seiscomp.io.MSeedRecord.TypeInfo():
+                    seiscomp.io.MSeedRecord(rec).write(os) 
+                else:
+                    rec.write(os)
                 continue
 
             dir, file = archive.location(rec.startTime(), rec.networkCode(
```

Maybe you can give it a try.

**Comment by gempa-jabe** [comment]
I have verifed that the returned data can be displayed with scrttv.

**Comment by damb** [comment]
Thanks. The patch seems to do its job if the `--stdout` CLI flag is used. Without the flag I get
```
Exception: 'SwigPyObject' object has no attribute 'access'
```

**Comment by damb** [comment]
> We do not know which type a recordstream returns.

I understand.

**Comment by gempa-jabe** [comment]
The exception is due to the patch and redefining `os`. Anyway, even after fixing it, it does work because of the same issue. And in that case it is not easy to write the record to a file object from Python. Maybe rejecting all non MiniSEED records is the best approach then.

**Comment by damb** [comment]
The question is if `scart` currently is able to write data other than MiniSEED (I need to admit, I didn't check all RecordStream implementations available, yet). If this is not the case we not we do not loose anything if rejecting all non MiniSEED records.

**Comment by gempa-jabe** [comment]
`scart` is actually a tool for "managing" an SDS archive and this is built from MiniSEED. So nothing else than MiniSEED is supported actually. Anyway I found your approach interesting to dump the downsampled records as MiniSEED to stdout. I think we will discard all non MiniSEED records for now.

**Comment by damb** [comment]
OT: Does SeisComP ship a module/tool which allows dumping MiniSEED data from any RecordStream implementation? Is there a 3rd party module available? I checked https://www.seiscomp.de/doc/modules.html but couldn't find anything better than the approach from above using `scart`.

**Comment by gempa-jabe** [comment]
No, there is no such tool. SeisComP uses records from the recordstream, it actually does not care about MiniSEED or any other format. That is the idea behind it. But implementing such a tool should be simple even with Python. scart with the patch from above does actually what you want I think.
