### ISSUE TITLE
[fdsnws] junk after XML data

### ISSUE THREAD

**Issue by andres-h** [SeisComP/main#22]
When using Python 3, fdsnws output has sometimes junk after XML data when non-ASCII characters appear in XML. The reason seems to be that in [Sink.write()](https://github.com/SeisComP/main/blob/0386bf512f88d3d2fa88c5442f7d4c0ce76041e8/apps/fdsnws/fdsnws/utils.py#L127), `data` is unicode, but `size` is in raw bytes.

The following workaround seems to solve the problem:

```python
class Sink(seiscomp.io.ExportSink):
    def __init__(self, request):
        seiscomp.io.ExportSink.__init__(self)
        self.request = request
        self.written = 0

    def write(self, data, size):
        try:
            if self.request._disconnected:
                return -1
            tmp = py3bstr(data)
            data = py3ustr(tmp[:size])
            writeTS(self.request, data)
            self.written += size
            return size

        except Exception as e:
            seiscomp.logging.error(str(e))
```

**Comment by gempa-stephan** [comment]
Please create a pull request for this fix which also adds a unicode test case for both the station and event service.

Also I would recommend to change the code to

```
dataBin = py3bstr(data)
writeTSBin(self.request, dataBin)
```

to avoid 2 unnecessary string conversions.
