### ISSUE TITLE
Adding a merge option to scdb

### ISSUE THREAD

**Issue by luca-s** [SeisComP/main#24]
Dear developers,

I would like to add an option to scdb to merge objects,  similarly to what scdispatch does in "update" mode. That is, scdb should compare the "objects to be written" to the content of the database and merge the differences.

Ideally I would copy the logic (visitor code) from scdispatch, but I have a dout regarding the update of objects. Currently scdb saves new objects to the database but fails when the same object id is found in the db. So I am not sure I would be able to update an existing object. 

Do you know if what I am planning to do is feasible?

Thanks!

**Comment by gempa-jabe** [comment]
Yes, it is feasible. scdispatch also checks if an objects is already available (and do an update) and if not it will add it. The code logic could actually be similar to scdispatch, only the dispatch itself would not send notifiers but write to the db directly.

**Comment by luca-s** [comment]
So it is feasible great! My only concern is that the [current db writer](https://github.com/SeisComP/main/blob/0386bf512f88d3d2fa88c5442f7d4c0ce76041e8/apps/tools/scdb/main.cpp#L55) in `scdb` extends `DataModel::DatabaseObjectWriter`, which [doesn't support](https://github.com/SeisComP/common/blob/6e44a973544073d7282d0ffd54039adce593d62a/libs/seiscomp/datamodel/databasearchive.cpp#L453) updates of objects, but only addition and deletion.

So, if I understand it correctly, I should create a new DatabaseObjectWriter that supports updates or I should modify `DataModel::DatabaseObjectWriter` for that.  Finally I can add the `scdispatch` update logic to `scdb` that makes use of this new db writer that supports objects updates.

**Comment by gempa-jabe** [comment]
Modify `DatabaseObjectWriter` to allow this merge operation would be the best option in my opinion. I am sure that it will break binary compatibility with the current libraries and must be targeted for SC 5. This would actually involve adding a new attribute (or replacing `_addObjects` with an enumeration and modifying `bool DatabaseObjectWriter::write(Object *object)`.

**Comment by luca-s** [comment]
Since I am on it, I would also like to add an option to select which objects to insert in the database (e.g. picks, origins, events, etc)

**Comment by luca-s** [comment]
I am closing this since we found another solution than changin `scdb`, thanks for the support
