### ISSUE TITLE
mysql: ResponsePAZ normalizationFactor should allow negative numbers

### ISSUE THREAD

**Issue by filefolder** [SeisComP/main#27]
Hi, currently I see that the normalizationFactor field in ResponsePAZ is type "double **unsigned**" BUT for some (older?) Guralp sensors the normalization factor (e.g. A0) is actually negative, and thus cannot be inserted into our database. 

(IMO it is EXTREMELY unwise of Guralp to have allowed negative A0 factors in the first place but that's here nor there.)

Can anyone recommend a method to quickly alter this table to just double? Also, are unsigned float/double etc tables depreciated in mysql now anyway? 

edit: ok I figured it out, 

1) log into mysql e.g. mysql -u root -p

2)
```
use your_sc_db_name; 
ALTER TABLE ResponsePAZ MODIFY COLUMN normalizationFactor DOUBLE;
```

**Comment by gempa-jabe** [comment]
Indeed MYSQL deprecated the use of unsigned floating point values. And as we are not using the unsigned constraint in PostgreSQL it makes sense to remove it. SEED also allows negative values I think.

**Comment by filefolder** [comment]
this is now fixed / closed
