### ISSUE TITLE
feature request: scxmldump read list of events/origin ids from a file

### ISSUE THREAD

**Issue by filefolder** [SeisComP/main#29]
When trying to export a large amount of events I often have issues with the eventID string being too long for my system kernel. Would it be possible to introduce an option to read from a file containing a list of IDs? 

something like `scxmldump  -d $conn -fPAMF -EF eventids.txt -o out.scxml`

I would like to help but I don't know how reading a file works in C at all 

Thanks in advance,

**Comment by gempa-jabe** [comment]
Is that still of interest or did you find an alternative that works for you? Passing a large list of event IDs would also result in a huge XML document which scxmldump must hold in memory. Dumping event by event into separate files might be a better solution.

**Comment by filefolder** [comment]
Yeah, I've just been writing events to individual files. It works well enough but one day hopefully we're all storing events in something other than XML.
