### ISSUE TITLE
fdsnws bug: event id is not reported anymore

### ISSUE THREAD

**Issue by luca-s** [SeisComP/main#33]
Dear developers,

I've noticed that in recent versions of SeisComP a bug was introduced in fdsnws and the event id is not reported anymore. That applies to both text and xml format. The last version that I know it was working fine is 4.4.0 then I tested version 4.7.0 and I saw this bug. I didn't have the time to check what commit caused the bug though.

thanks
Luca

**Comment by luca-s** [comment]
Just a clarification: when I say "event id is not reported" I mean that it is now an empty string, but it used to be the full event id

**Comment by gempa-jabe** [comment]
Can you give an example request that does not work anymore?

**Comment by gempa-jabe** [comment]
@gempa-stephan, please check.

**Comment by luca-s** [comment]
Text output
![Screenshot from 2021-12-03 17-05-14](https://user-images.githubusercontent.com/15273575/144634385-6766e420-bb18-4c90-b4e1-9afd8de6c4ca.png)
csv output
![Screenshot from 2021-12-03 17-05-33](https://user-images.githubusercontent.com/15273575/144634424-f90f51ab-e0b7-4e30-bd6e-2e2e0357b02a.png)
Quakeml output
![Screenshot from 2021-12-03 17-05-49](https://user-images.githubusercontent.com/15273575/144634446-8a5da4bb-bf1a-4b66-996a-bd49ef735ba3.png)
Seiscomp XML output

![Screenshot from 2021-12-03 17-06-16](https://user-images.githubusercontent.com/15273575/144634493-6d55caa5-ab8e-45bd-8573-76669cfa0827.png)

**Comment by luca-s** [comment]
And with version 4.4.0...

![image](https://user-images.githubusercontent.com/15273575/144634806-12b25e2d-d89b-4709-a6b6-804a646b455b.png)

![image](https://user-images.githubusercontent.com/15273575/144634935-2b283d3e-dbd7-4ae4-b3c0-c177f93c5b7a.png)

![image](https://user-images.githubusercontent.com/15273575/144634992-9501f37e-1373-4da6-8762-dd175176c9de.png)

![image](https://user-images.githubusercontent.com/15273575/144635042-3cbe4ad6-b44f-46e7-99dc-377865748469.png)

**Comment by gempa-jabe** [comment]
Does scxmldump with 4.7 show the publicID of the event? I have tested it with the current master and I see eventIDs with fdsnws. I am going to test with the latest release 4.8.

**Comment by gempa-jabe** [comment]
With 4.7.4 I see all eventIDs as well.

**Comment by gempa-jabe** [comment]
Same behaviour with 4.8.0. I can't reproduce it. Maybe you can create an example database (SQlite3) which exhibits the issue so that we can test with it. I think two events or even just one should be enough.

**Comment by gempa-jabe** [comment]
I think I found the issue. It only affects PostgreSQL. Can you please try to change https://github.com/SeisComP/main/blob/master/apps/fdsnws/fdsnws/event.py#L761 to `AS m_publicID` and check if it works?

**Comment by luca-s** [comment]
That's it, that fixed the issue. Thanks a lot @gempa-jabe
