### ISSUE TITLE
lib boost error during update-config

### ISSUE THREAD

**Issue by filefolder** [SeisComP/main#34]
sorry if 'main' is the incorrect area for this

near the end of the update-config output I'm getting this error right after the warnings about plugins being loaded already

python3.8: /usr/include/boost/smart_ptr/intrusive_ptr.hpp:199: T* boost::intrusive_ptr<T>::operator->() const [with T = Seiscomp::DataModel::Config]: Assertion `px != 0' failed.

it looks like there is maybe a typo with ` being used instead of ' but I'm just guessing

ubuntu 20.04 & libboost.dev 1.71.0.0ubuntu2 & latest master branch as of this post

**Comment by gempa-jabe** [comment]
That is not a typo, that is an error in the code. The "typo" is just the assertion message from boost. Are you getting this if you run `seiscomp update-config trunk`? Do you have bindings configured? Was that an installation with an empty config database or a regular run just with another SeisComP version?

**Comment by filefolder** [comment]
Hi, command with trunk works / no error. There are bindings and inventory configured, it's been the same setup for some time but I think some aspects of the system may have been upgraded last month. The error didn't occur until I recompiled the latest master. Sorry I can't be of more help.

**Comment by gempa-jabe** [comment]
Don't worry, you can be of more help ;)

Does `seiscomp update-config inventory` work? If it is working can you post the complete output of `seiscomp update-config`? I need to know which config module produces the error. You can remove sensitive data from the output.

**Comment by filefolder** [comment]
update-config inventory works. 

here's the normal output, snipped some redundant information
```
$ seiscomp update-config
* starting kernel modules
scmaster is already running
* configure kernel
* configure scmaster
INFO: checking DB schema version of queue: production
  * check database write access ... OK
  * database schema version is 0.12
  * last migration version is 0.12
  * schema up-to-date
* configure inventory
WARNING: etc/inventory/README ignored: wrong extension
Parsing etc/inventory/7B_SKIPPY_1993.xml ... done
....
Parsing etc/inventory/1Q_AQT_2016.xml ... done
Merging inventory ... done
Synchronising inventory ... done
Removing remaining objects ... done
123 notifiers available
Sending notifiers: 100%
No new key file added and no old key file removed
* configure access
* configure diskmon
* configure ew2sc
* configure fdsnws
* configure ql2sc
* configure scalert
* configure scamp
* configure scautoloc
* configure scautopick
* configure scdb
* configure scenvelope
* configure scevent
* configure scevtlog
* configure scimex
* configure scimport
* configure scm
* configure scmag
* configure scproclat
* configure scqc
* configure screloc
* configure scrtdd
* configure scsohlog
* configure scvoice
* configure scvsmag
* configure scvsmaglog
* configure scwfas
* configure scwfparam
* configure seedlink
+ network AU
  + station CAAN Eighty Mile Beach
    + source chain as GAseedlink
...
+ network ND
  + station KOUNC administrative code : 98812
    + source chain as ird_sl
* configure slarchive
* configure slmon
* configure trunk
00:26:54 [warning] The plugin dbmysql has been loaded already
00:26:54 [warning] The plugin locnll has been loaded already
python3.8: /usr/include/boost/smart_ptr/intrusive_ptr.hpp:199: T* boost::intrusive_ptr<T>::operator->() const [with T = Seiscomp::DataModel::Config]: Assertion `px != 0' failed.
```
what is sort of interesting, and i have this problem on other installs that do not have this glitch, there are always persistent "notifiers available" (here 123) despite syncing keys etc. I assume this is a separate issue though.

**Comment by gempa-jabe** [comment]
So the issue seems to be with `update-config trunk`. Please try again with `seiscomp --debug update-config trunk` and if it crashes then I am interested in the backtrace (Traceback). Otherwise run `seiscomp --debug update-config` and post the backtrace.

Regarding the other issue: you can run `scinv sync --create-notifier -o temp.xml -d mysql://localhost/seiscomp` and check what notifiers it creates. You can furthermore check `scmaster.log` for some database related issues with updating the inventory.

**Comment by filefolder** [comment]
update-config:

```
01:38:26 [info]
Plugins:
--------
 [1]
  description: MySQL database driver
       author: GFZ Potsdam <seiscomp-devel@gfz-potsdam.de>
      version: 0.9.2
          API: 15.0.0
 [2]
  description: Locator implementation using NonLinLoc by Anthony Lomax (http://alomax.free.fr/nlloc/)
       author: Jan Becker, gempa GmbH
      version: 0.7.2
          API: 15.0.0

01:38:26 [info] Connect to messaging
01:38:26 [debug] Trying to connect to _sccfgupd_@scmp://localhost:18180/production with primary group =
01:38:26 [debug] Attempt to connect to localhost:18180/production
01:38:26 [debug] Registered clientname: _sccfgupd_
01:38:26 [info] Outgoing messages are encoded to match schema version 0.12
01:38:26 [info] Want to flush 0 backlog messages
01:38:26 [info] Connect to database
01:38:26 [info] Received database service parameters
01:38:26 [info] Trying to connect to mysql database
01:38:26 [debug] Connected to name:******@localhost:3306/seiscomp (Localhost via UNIX socket)
01:38:26 [debug] Found database version v0.12
01:38:26 [info] Connected successfully
01:38:26 [info] Loading configuration module
python3.8: /usr/include/boost/smart_ptr/intrusive_ptr.hpp:199: T* boost::intrusive_ptr<T>::operator->() const [with T = Seiscomp::DataModel::Config]: Assertion `px != 0' failed.
```

update-config trunk works fine. i'll have to investigate the trackback etc in the morning

**Comment by gempa-jabe** [comment]
The above is the output of which command?

**Comment by filefolder** [comment]
the output above is `update-config`

`update config trunk` has no error / works fine. 

I tried again systematically disabling all running extraneous modules one at a time, no change. I also cleared the entire inventory, no change. This is not a production machine so I am willing to be dramatic. 

I have attempted to do a backtrace on the error via gdb but I can't seem to get it to work, admittedly I am not very adept at such things.

**Comment by gempa-jabe** [comment]
Actually the error is from Python, so from a Swig wrapped call in a Python script. Does `seiscomp --debug update-config` show a Python backtrace? As the username of the script application is `_sccfgupd_` it can only be `trunk` or `access`.

**Comment by filefolder** [comment]
When I add --debug it doesn't actually change anything as far as I can tell, is that a valid flag here? I had to turn on the verbosity level elsewhere to get those messages to show. 

The above message I posted seems to be as much detail as I can get. 

Nothing of interest in var/log else here's the latest from scmaster.log
```

2022/01/26 20:30:53 [debug/Wired] [http] GET /production HTTP/1.1
2022/01/26 20:30:53 [debug/Wired] [http] Host: localhost
2022/01/26 20:30:53 [debug/Wired] [http] Upgrade: websocket
2022/01/26 20:30:53 [debug/Wired] [http] Connection: Upgrade
2022/01/26 20:30:53 [debug/Wired] [http] Connection upgrade requested
2022/01/26 20:30:53 [debug/Wired] [http] Sec-WebSocket-Protocol: scmp
2022/01/26 20:30:53 [debug/Wired] [http] Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==
2022/01/26 20:30:53 [debug/Wired] [http] Sec-WebSocket-Version: 13
2022/01/26 20:30:53 [debug/Wired] [0x55f9245ddf20] GET /production
2022/01/26 20:30:53 [debug/MASTER] Connect client '_sccfgupd_' to 'production'
2022/01/26 20:30:53 [debug/Wire] [reactor] move 0x0x55f9245ddf20 to 0x0x55f9243e3220
2022/01/26 20:30:53 [debug/Wire] [server] active sessions/sockets: 0/1
2022/01/26 20:30:53 [debug/Wire] [reactor] active sessions/sockets: 8/8
2022/01/26 20:30:53 [debug/BROKER] _sccfgupd_: disconnect on close
2022/01/26 20:30:53 [debug/MASTER] Disconnect client '_sccfgupd_'
2022/01/26 20:30:53 [info/Wire] [reactor] removed session 0x55f9245ddf20
2022/01/26 20:30:53 [debug/Wire] [reactor] active sessions/sockets: 7/7
2022/01/26 20:31:01 [info/dbstore] DBPLUGIN (aps,ups,dps,errors) 0.00 0.00 0.00 0.00
2022/01/26 20:31:13 [info/dbstore] DBPLUGIN (aps,ups,dps,errors) 0.00 0.00 0.00 0.00
2022/01/26 20:31:26 [info/dbstore] DBPLUGIN (aps,ups,dps,errors) 0.00 0.00 0.00 0.00
2022/01/26 20:31:38 [info/dbstore] DBPLUGIN (aps,ups,dps,errors) 0.00 0.00 0.00 0.00
2022/01/26 20:31:51 [info/dbstore] DBPLUGIN (aps,ups,dps,errors) 0.00 0.00 0.00 0.00
2022/01/26 20:32:04 [info/dbstore] DBPLUGIN (aps,ups,dps,errors) 0.00 0.00 0.00 0.00
2022/01/26 20:32:16 [info/dbstore] DBPLUGIN (aps,ups,dps,errors) 0.00 0.00 0.00 0.00
2022/01/26 20:32:29 [info/dbstore] DBPLUGIN (aps,ups,dps,errors) 0.00 0.00 0.00 0.00
2022/01/26 20:32:41 [info/dbstore] DBPLUGIN (aps,ups,dps,errors) 0.00 0.00 0.00 0.00
2022/01/26 20:32:53 [info/dbstore] DBPLUGIN (aps,ups,dps,errors) 0.00 0.00 0.00 0.00
2022/01/26 20:33:06 [info/dbstore] DBPLUGIN (aps,ups,dps,errors) 0.00 0.00 0.00 0.00
2022/01/26 20:33:18 [info/dbstore] DBPLUGIN (aps,ups,dps,errors) 0.00 0.00 0.00 0.00
2022/01/26 20:33:31 [info/dbstore] DBPLUGIN (aps,ups,dps,errors) 0.00 0.00 0.00 0.00
2022/01/26 20:33:43 [info/dbstore] DBPLUGIN (aps,ups,dps,errors) 0.00 0.00 0.00 0.00
```

if you can suggest any packages to update or reinstall, I more than willing. I just reinstalled libboost but it didn't help.

**Comment by gempa-jabe** [comment]
No, you don't need to reinstall any package. I would like to know where the error occurs. It must be somewhere in a init script. `--debug` right after `seiscomp` is valid, yes. It will then output the Python backtrace if a Python script crashes. That has nothing to to with e.g. `scautopick --debug`.

**Comment by gempa-jabe** [comment]
I could reproduce it, yeah! Stay tuned ...

**Comment by gempa-jabe** [comment]
Please upgrade your sources and try again. The [common repository](https://github.com/SeisComP/common) has changed and the bug has been fixed there.

**Comment by gempa-jabe** [comment]
With sources I mean the source code and you need to recompile ...

**Comment by filefolder** [comment]
yep that fixed it! well done, thought i almost had ya stumped for a minute there. feel free to close at your discretion
