### ISSUE TITLE
Hiding protected member function

### ISSUE THREAD

**Issue by damb** [SeisComP/main#35]
Hi,

both
https://github.com/SeisComP/main/blob/2b934aadda0b70a6612249269cb4fc6638f49889/apps/processing/scautopick/picker.h#L92
and
https://github.com/SeisComP/main/blob/2b934aadda0b70a6612249269cb4fc6638f49889/apps/processing/scqc/qctool.h#L78
hide the protected member function from https://github.com/SeisComP/common/blob/9f30d6a6fcab3307cd868891370eb8e64a6c21dd/libs/seiscomp/processing/application.h#L98. Is this on purpose?

**Comment by gempa-jabe** [comment]
As those are private classes of the application, it does not make a difference. They could be made protected as well. Do you see any problems with it?

**Comment by damb** [comment]
No, at the moment I don't see a problem with it. I simply was wondering whether there is something I'm not aware of. In base cases there is public inheritance involved (from `Processing::Application`). Therefore, I would expect member functions to be overridden with the same accessibility.

**Comment by gempa-jabe** [comment]
You are right with your expectation. Sometimes developers take weird decisions ;)

**Comment by damb** [comment]
See also https://isocpp.org/wiki/faq/proper-inheritance#hiding-inherited-public.

**Comment by gempa-jabe** [comment]
We are actually not hiding public functions but make protected functions private. I agree with the statement made and we can fix that although it should not have any consequences for those classes as their are leafs in the inheritance tree.

**Comment by gempa-jabe** [comment]
We are actually not hiding public functions but make protected functions private. I agree with the statement made and we can fix that although it should not have any consequences for those classes as their are leafs in the inheritance tree and private to the application.
