### ISSUE TITLE
BUG: scdbstrip doesn't consider --days option

### ISSUE THREAD

**Issue by luca-s** [SeisComP/main#39]
Dear developers,

a bug has been recently introduced in `scdbstrip`, where the `--days` option is not considered if that is the only option provided and the code defaults to the 30 days period instead.

The bug was introduced with the inclusion of the new option  `--datetime` and the line responsible for the bug is [this](https://github.com/SeisComP/main/blob/b335c509bab8908265752f876662c21acadaf758/apps/python/scdbstrip.py#L486), which makes the period 30 days regardless of the value of self._daysToKeep.

Luca

**Comment by gempa-jabe** [comment]
I think a check is missing to also check `daysToKeep is None`. @gempa-dirk

**Comment by gempa-dirk** [comment]
@luca-s We will provide a fix.

**Comment by gempa-dirk** [comment]
The fix has been made and will be provided with an upcoming release.
