### ISSUE TITLE
[documentation] external links in documentation broken?

### ISSUE THREAD

**Issue by FMassin** [SeisComP/main#45]
Hello,

Some of the external links in documentation seem to be broken in seiscomp.de but not in docs.gempa.de? E.g. https://www.seiscomp.de/doc/apps/fdsnws.html :
> FDSN specifications can be found on [:cite:t:`fdsn`](https://www.seiscomp.de/doc/apps/fdsnws.html#id6).

Is this something that should be fixed?

Cheers

Fred

**Comment by andres-h** [comment]
Has been fixed.
