### ISSUE TITLE
[scmssort] version 5.3 breaks backward compatibility 

### ISSUE THREAD

**Issue by luca-s** [SeisComP/main#56]
I have just noticed that in `scmssort` v5.3.0 is mandatory to specify `-` argument to read from standard input. In previous version that was the default behaviour and the change breaks existing scripts.

**Comment by gempa-stephan** [comment]
This problem has been rectified 2 week ago, see c8a42eadefedf5f075c75085accbf77121c4fe06. You might try the latest version which includes further code improvements and different log levels.
