### ISSUE TITLE
scautopick stop working after ~3 hours

### ISSUE THREAD

**Issue by luca-s** [SeisComP/main#58]
Dear developers,

this issue is something that I am going to debug myself, but I would like to double check first with you in case you have an idea already of what the problem could be.

The bug happens all the time: I start scautopick and after  ~3 hours it stops producing picks. The process is still alive though. The interesting thing is that I am using data at 200.000hz. Do you know if there are internal counters that might reach the limits too soon with this high frequency data?

thanks
Luca

**Comment by jsaul** [comment]
Hi Luca,
good catch! 200k*3600*3 is very close to 2**31 so you are probably on the right track that some counter is be the culprit.

`find ~/seiscomp/include/seiscomp -name "*.h"|xargs grep sampleCount`

Take your pick. :)   Maybe 

https://github.com/SeisComP/common/blob/master/libs/seiscomp/math/filter/stalta.cpp#L90
https://github.com/SeisComP/common/blob/master/libs/seiscomp/math/filter/stalta.cpp#L97

as a start... The developer on duty certainly did not have such large sample count on his radar, let alone the possibility that it may become negative. I am pretty sure that changing the type of `_sampleCount` to `int64_t` will already fix the issue. Would you mind trying that out?

Thanks for the hint!
Joachim

**Comment by gempa-jabe** [comment]
I would just skip increasing the samplecount once it is not needed anymore, after it is >= numLta. If a lta time window for 1Mhz data of 30 minutes should be supported then we can use int64 anyway. Changing the count possibly breaks binary compatibility.

**Comment by luca-s** [comment]
Thank you, I had the feeling that you knew something already :) I will test it and report back.

**Comment by luca-s** [comment]
I confirm that is the bug

**Comment by gempa-jabe** [comment]
I have fixed it hopefully, please give it another try. The fix is in common repo.

**Comment by luca-s** [comment]
Thank you!
