### ISSUE TITLE
[scdbstrip] linting went wrong

### ISSUE THREAD

**Issue by luca-s** [SeisComP/main#72]
I have just noticed the results of linting scdbstrip and something went wrong. That doesn't break the code and it doesn't bother me. However, since the purpose of the change was "linting", it would be better to check why the tool made such modification and avoid that in the future.

Inconsistent use of `\` at the end of a line (some lines have it, but other don't):

Examples  (but there are many more):
![image](https://github.com/SeisComP/main/assets/15273575/261a658b-421e-40c9-a37d-ae9d52a69e9d)

![image](https://github.com/SeisComP/main/assets/15273575/5356ff5a-14be-475b-abd3-99d714a535a8)

Spurious trailing comma ",":

Examples (but there are many more):
![image](https://github.com/SeisComP/main/assets/15273575/4b3e0c28-a3f3-4868-838f-68bd1a1d14f0)

**Comment by gempa-jabe** [comment]
The Python guys use `black`, `flynt` and `pylint` for linting which comes with best practices. We do not provide our own linting rules, only disable some warnings. Some stuff might look weird and we could look up every single decision by the tool but as long as it is still working, we trust it. Do you have a recommendation to avoid those issues?
