### ISSUE TITLE
fdsnws crash when availability enabled

### ISSUE THREAD

**Issue by filefolder** [SeisComP/main#74]
Hi, noticing now in 6.0.3 that when the availability service is enabled, fdsnws crashes and won't start. 

Here is the fdsnws.log message:

```
2023/12/15 10:22:37 [error/Core] Time::fromString: buffer size exceeded: 171 > 63
2023/12/15 10:22:37 [error/Core] Time::fromString: buffer size exceeded: 171 > 63
2023/12/15 10:52:54 [error/Core] Time::fromString: buffer size exceeded: 134 > 63
2023/12/15 10:52:54 [error/Core] Time::fromString: buffer size exceeded: 134 > 63
```

It's just those four messages. This is following a fresh run of `scardac`... I suspect a datetime string got garbled in the (mysql) database somewhere but I am not fluent enough in mysql to know how to check. Never had the issue previously.

**Comment by gempa-stephan** [comment]
Please start fdsnws on the command line using the `--trace` switch and attach the output:

```
seiscomp exec fdsnws --trace
```

You may also export your availability information and check the dates in the XML or attach the file here:

```
seiscomp exec scxmldump -Y --with-segments -d localhost -f -o /tmp/availability.xml
```

**Comment by filefolder** [comment]
Thanks--

```
$ seiscomp start fdsnws --trace
starting fdsnws
Summary: 0 modules started
```
Not much there. The log just shows it shutdown immediately this time

`2023/12/15 19:17:39 [notice/Application] Shutdown`

attaching [availability.xml.gz](https://github.com/SeisComP/main/files/13682605/availability.xml.gz) 

cursory start/stop/updated searches via `grep 'updated' availability.xml | awk 'length($0) > 52 {print $0}'` not showing anything too unusual yet

**Comment by gempa-jabe** [comment]
You can't start a module with an option. Use `seiscomp exec fdsnws --trace` on the command line to run it in foreground.

**Comment by filefolder** [comment]
very sorry, attempting this post-christmas party for some reason

```
$ seiscomp exec fdsnws --trace
can't serve availabilty without dataAvailability.enable set to true
```
so doesn't look like a db or scardac issue at all

not sure I understand what has happened. via ssconfig, checking the `serveAvailability` box sets `serveAvailability = true` in fdsnws.cfg, but `dataAvailability.enable` in fdsnws.cfg was still set to `false`. there doesn't seem to be a `dataAvailability` setting via ssconfig. manually changing this to `true` via a text editor solved the problem

**Comment by gempa-jabe** [comment]
OK, thank you. We will look into that and fix it.

**Comment by filefolder** [comment]
ah. as usual the error is mine. i missed it as it was in a slightly different section. closing!
