### ISSUE TITLE
ew2sc vs. ew2sc3

### ISSUE THREAD

**Issue by stefanisti** [SeisComP/main#8]
Sorry if this isn't the right sc git branch to report this small version 4 issue.

It is ew2sc in scconfig's "System" tab, however in the Modules tab it is "ew2sc3".

One can work around this with 
seiscomp alias create ew2sc3 ew2sc
and then start up in System "ew2sc3" but clearly this is just a simple bug fix in the right place in the code to change the Modules to look for ew2sc.

**Comment by gempa-jabe** [comment]
The application is actually in another repository: https://github.com/SeisComP/contrib-ipgp.
Anyway, thanks for the information, I am going to fix that. It is actually just the name of the module in `etc/descriptions/ew2sc.xml` which is wrong.

**Comment by gempa-jabe** [comment]
The fix is here: https://github.com/SeisComP/contrib-ipgp/commit/fc31215d453976ab9f6fb68d5b7086aa24442953.
